mancala3 : mancala3.c
	gcc mancala3.c -o mancala3
lapToSg : mancala3.c
	scp mancala3.c osbalaji@stargate.cs.usfca.edu:/home/osbalaji/mancala3.c
sgToLap : mancala3
	scp osbalaji@stargate.cs.usfca.edu:/home/osbalaji/mancala3.c mancala3.c
