
memspeed: memspeed.c
	gcc memspeed.c -o memspeed

fifo: fifo.h fifo.c
	gcc fifo.c -o fifo

testfifo: testfifo.c fifo.c fifo.h
	gcc testfifo.c fifo.c -o testfifo

runfifo: runfifo.c fifo.c fifo.h
	gcc runfifo.c fifo.c -o runfifo
